blog_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
  	resources :comments
  	resources :likes
  end
  
  root "post#index"
  
  get '/about', to: 'pages#about'
end

blog_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true
	validates :body, presence: true
end

blog_app/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

blog_app/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many  :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true

	has_attached_file :image, styles: { medium: "300x400#", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

blog_app/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:visitor, :author, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :posts
  validates :name, presence: true
  has_many :likes, dependent: :destroy

  def set_default_role
    self.role ||= :visitor
  end
end

blog_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

blog_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_post)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_post
    params.require(:comment).permit(:name, :body)
  end
end

blog_app/app/controllers/likes_controller.rb
# class LikesController < ApplicationController
#   before_action :set_post
#   before_action :find_like, only: [:destroy]

#   def create
#     if already_liked?
#       flash[:notice] = "You can't like more than once"
#     else
#       @post.likes.create(user_id: current_user.id)
#     end
#     redirect_to post_path(@post)
#   end

#   def destroy
#   if !(already_liked?)
#     flash[:notice] = "Cannot unlike"
#   else
#     @like.destroy
#   end
#     redirect_to post_path(@post)
#   end

#   private

#   def set_post
#     @post = Post.find(params[:post_id])
#   end

#   def already_liked?
#     Like.where(user_id: current_user.id, post_id:
#     params[:post_id]).exists?
#   end

#   def find_like
#     @like = @post.likes.find(params[:id])
#   end

# end

blog_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

blog_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.includes(:user).all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

blog_app/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_app/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_app/app/helpers/likes_helper.rb
module LikesHelper
end

blog_app/app/helpers/pages_helper.rb
module PagesHelper
end

blog_app/app/helpers/posts_helper.rb
module PostsHelper
end

blog_app/app/views/comments/_comment.html.erb
<div class="comment_clearfix">
	<div class="comment_content">
	<p class="comment_clearfix"><strong><%= comment.name %></strong> :
	<p class="comment_body"><%= comment.body %></p>
	<p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago </p>
	</div>
	<br>
	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment],
										method: :delete,
										class: "button",
										data: { confirm: "are you sure?" } %>
	
	</p>
	<% end %>
	<br>
</div>

blog_app/app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <% if !user_signed_in? %>
      <button><%= link_to "Create Comment", new_user_registration_path %></button>
    <% else %>
      <%= f.submit %>
    <% end %>
  </p>
<% end %>

blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="topnav">
	  <%= link_to 'Blog', posts_path %>
	  <%= link_to 'About', about_path %>
	  <% if !user_signed_in? %>
		  <%= link_to 'Sign Up', new_user_registration_path %>
		  <%= link_to 'Login', new_user_session_path %>
	  <% else %>
		  <%= link_to "Settings", edit_user_registration_path %>
		  <%= link_to 'New Post', new_post_path %>
		  <%= link_to "Logout", destroy_user_session_path %>
		<% end %>
		  
	</div>

<%= yield %>

</body>
</html>

blog_app/app/views/pages/about.html.erb
<div id="profile_image">
		<%= image_tag "logo.png" %>
</div>

<div id="content">
	<h1>Hey, its chriss</h1>
	<p>
		Michael Hartl is the creator of the Ruby on Rails Tutorial, one of the leading introductions to web development, and is cofounder and principal author at LearnEnough.com. Previously, he was a physics instructor at the California Institute of Technology (Caltech), where he received a Lifetime Achievement Award for Excellence in Teaching. He is a graduate of Harvard College, has a Ph.D. in Physics from Caltech, and is an alumnus of the Y Combinator entrepreneur program.
	</p>
</div>

blog_app/app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image  %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog_app/app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

blog_app/app/views/posts/index.html.erb
<h1 align="center">All Posts</h1>

<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>

<body>
<table align="center">
	<thead>
		<tr>
			<th style="width:30%">Title</th>
			<th style="width:30%">Written by</th>
			<th style="width:30%">Time</th>
			<th style="width:30%">Likes</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= link_to post.title, post %></td>
				<td><%= post.user.name %></td>
				<td><%= post.created_at.strftime("%B, %d, %Y")%></td>
				<td><%= post.likes.count %></td>
			</tr>
		<% end %>
	</tbody>
</table><br>

</body>

blog_app/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<strong><%= link_to 'Back', posts_path %></strong>

blog_app/app/views/posts/show.html.erb
<div id="post_content" >
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p>
    <%= image_tag @post.image.url(:medium) %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>
  <p> 
  <h4><%= @post.likes.count %></h4>
  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>

  <div id="comments">
    <h4><%= @post.comments.count %> Comments</h4>
    <%= render @post.comments %>

    <h3>Add a comments</h3>
    <%= render "comments/form" %>
  </div>


  <strong><%= link_to 'Back', posts_path %></strong>
</div>